### ISSUE TITLE
Creating the Point class

### ISSUE THREAD

**Issue by Skwierc1** [Skwierc1/firstproject#5]
So far the only requirements for the point class is setting the point class up to contain an x and y value.
The x and y values should have getters and setters. ex: get_x, set_y
Initialize the possible functions for the point class, just pass them for now.

**Comment by Skwierc1** [comment]
Decided that the point class will be setup to handle multidimensional space. Instead of taking just x and y, the point class will accept a tuple of dimentions based off of the dimensions of the space they user is working in.

**Comment by Joeymbronco24** [comment]
This class was fully completed with TDD file associated with it for testing.
